#!/bin/bash

echo "🐳 Docker Health Check Fix for Ubuntu Server"
echo "============================================"

echo ""
echo "This script fixes the Docker health check issue by:"
echo "1. ✅ Ensuring /health endpoint exists and is not protected"
echo "2. ✅ Using a robust health check command"
echo "3. ✅ Adding proper timing and retries"
echo ""

echo "📋 Current Configuration:"
echo "========================"

echo ""
echo "✅ Backend Health Endpoint (main.go):"
echo "   - /health endpoint returns 'OK'"
echo "   - /ping endpoint returns 'pong'"
echo "   - Both endpoints require NO authentication"
echo "   - Both endpoints available on HTTP port 8080"

echo ""
echo "✅ Docker Health Check (docker-compose.yml):"
echo "   - Uses: wget --quiet --tries=1 --spider http://localhost:8080/health"
echo "   - Timeout: 10s"
echo "   - Retries: 5"
echo "   - Start period: 30s (gives server time to start)"

echo ""
echo "🔧 Test Commands for Your Ubuntu Server:"
echo "======================================="

echo ""
echo "1. Stop any existing containers:"
echo "   sudo docker-compose down"

echo ""
echo "2. Clean up and rebuild:"
echo "   sudo docker system prune -f"
echo "   sudo docker-compose build --no-cache"

echo ""
echo "3. Start with verbose output:"
echo "   sudo docker-compose up"

echo ""
echo "4. In another terminal, monitor health:"
echo "   watch 'sudo docker-compose ps'"

echo ""
echo "5. Test health endpoint manually:"
echo "   sudo docker-compose exec backend wget -qO- http://localhost:8080/health"
echo "   sudo docker-compose exec backend wget -qO- http://localhost:8080/ping"

echo ""
echo "6. Check backend logs:"
echo "   sudo docker-compose logs backend"

echo ""
echo "🩺 Debug Health Check Issues:"
echo "============================"

echo ""
echo "If health check still fails, try these debug commands on your server:"
echo ""
echo "Check if backend is listening on 8080:"
echo "   sudo docker-compose exec backend netstat -ln | grep 8080"
echo ""
echo "Test health check command manually:"
echo "   sudo docker-compose exec backend sh -c 'wget --quiet --tries=1 --spider http://localhost:8080/health && echo SUCCESS || echo FAILED'"
echo ""
echo "Check container internal connectivity:"
echo "   sudo docker-compose exec backend curl -v http://localhost:8080/health"

echo ""
echo "🎯 Expected Results:"
echo "=================="
echo "✅ Backend container should show (healthy) status"
echo "✅ Frontend should start after backend is healthy"
echo "✅ Health endpoints should return OK/pong"

echo ""
echo "🔍 Common Issues & Solutions:"
echo "=========================="
echo "❌ If 'connection refused': Server not binding to port"
echo "   - Check backend logs for startup errors"
echo "   - Verify HTTPS_PORT and port binding"
echo ""
echo "❌ If 'timeout': Server too slow to start"
echo "   - Increase start_period in docker-compose.yml"
echo "   - Check server startup time in logs"
echo ""
echo "❌ If '404 not found': Route not registered"
echo "   - Verify /health endpoint in main.go"
echo "   - Check if CORS middleware interferes"

echo ""
echo "✅ Ready for testing on your Ubuntu server!"
