global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'sphere-of-influence-backend'
    static_configs:
      - targets: ['backend:8443']
    scheme: https
    tls_config:
      insecure_skip_verify: true
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'nginx'
    static_configs:
      - targets: ['frontend:80']
    metrics_path: /nginx_status
    scrape_interval: 30s
